# Generated by Django 5.1.3 on 2024-12-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='text',
        ),
    ]
